### ISSUE TITLE
Regarding prompts to the trained model.

### ISSUE THREAD

**Issue by rohan1100** [xiaohui-victor-li/FinDKG#2]
Hey author how do i give prompts comprising of financial documents so that i can get knowledge graph out of it (i have trained the model on the FinDKG dataset that you provided). What are the next steps to get knowledge graph out of financial douments that are in .txt format?

**Comment by xiaohui-victor-li** [comment]
Hello, thanks for your interest in our paper!

You can replace the <input_text> in the [prompt](https://huggingface.co/victorlxh/ICKG-v3.2) with your document corpus (e.g., financial news article). The output will be in a JSON format as a list of the extracted event triplets. You can use python to process and store the output into the desired format like .txt.
