### ISSUE TITLE
ICKG fine-tuning dataset?

### ISSUE THREAD

**Issue by gabrielgrant** [xiaohui-victor-li/FinDKG#3]
Very interesting work!
Is the dataset used to fine-tune ICKG available somewhere? Or would you be open to releasing it?

Specifically talking about the "~5K instruction-following demonstrations including KG construction input document and extracted KG triplets as response output"

This is the repo linked from [the ICKG HuggingFace page](https://huggingface.co/victorlxh/ICKG-v3.2). I'm not actually seeing any code or data in this repo directly related to ICKG (although I assume FinDKG dataset is based on output of the model?), so apologies if this isn't the right place to ask the question

**Comment by xiaohui-victor-li** [comment]
Thank you Gabriel for your interest in our paper. The fine-tuning data is not released as we do not have the release rights. 

You can generate the training data based on the prompt provided with your own document corpus.

**Comment by gabrielgrant** [comment]
Ah, gotcha. Thanks for the reply!
